name: Deploy to Cloud Run

on:
  push:
    branches: [main]  # or use 'master' if that's your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: calculator-465217
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and Push Docker image to Artifact Registry
      run: |
        gcloud builds submit --tag gcr.io/calculator-465217/power-calculator

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy power-calculator \
          --image gcr.io/calculator-465217/power-calculator \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
